image:
  file: .gitpod/.gitpod.dockerfile
  context: .gitpod/
ports:
  - port: 4000
tasks:
  - name: postgres
    init: |
      # Initialising DB
      # Awaiting for port 5432 to be available
      gp ports await 5432

      # Adding postgres user to the database
      psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'mysecretpassword';"       

      # Synchronising with the next task
      gp sync-done DB

  - name: Phx
    init: |
      # Installing Elixir global dependencies
      mix local.hex --force
      mix local.rebar --force
      mix archive.install hex phx_new --force

      # Installing Elixir local dependencies
      mix deps.get && mix deps.compile

      # Waiting for the DB user to be created 
      gp sync-await DB

      # Migrating the tables to the DB
      mix ecto.create && mix ecto.migrate

      # Running seeds
      mix run apps/stygian/priv/repo/seeds.exs

      # Installing client packages
      npm install --prefix apps/stygian_web/assets

    command: |
      # Starting Phoenix
      export PATH="$HOME/.asdf/shims:$PATH"
      mix phx.server
