image:
  file: .gitpod/.gitpod.dockerfile
  context: .gitpod/
ports:
  - port: 4000
tasks:
  - name: postgres
    init: >
      #init db
      psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'mysecretpassword';" 
      gp sync-done DB
      
  - name: Phx
    env: 
      PATH: 
    init: >
      # Setting up PATH
      export PATH="$HOME/.asdf/shims:$PATH"

      # Installing Phoenix packages
      mix local.hex --force
      mix local.rebar --force
      mix archive.install hex phx_new
      
      # Installing Back End dependencies
      mix deps.get && mix deps.compile

      # Waiting for DB to be finished
      gp sync-done DB
      
      # Creating and migrating database
      mix ecto.create && mix ecto.migrate
      
      mix run apps/stygian/priv/repo/seeds.exs
      
      # Installing Front End dependencies
      npm install --prefix apps/stygian_web/assets
    command: >
      # Setting up PATH
      export PATH="$HOME/.asdf/shims:$PATH"

      mix phx.server