image:
  file: .gitpod/.gitpod.dockerfile
  context: .gitpod/
ports:
  - port: 4000
tasks:
  - name: postgres
    init: |
      gp sync-await ZSH

      # Initialising DB
      psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'mysecretpassword';" 
      gp sync-done DB

  - name: Phx
    init: |
      # Waiting for the DB user to be created 
      gp sync-await DB

      # Migrating the tables to the DB
      mix ecto.create && mix ecto.migrate

      # Running seeds
      mix run apps/stygian/priv/repo/seeds.exs

      # Installing client packages
      npm install --prefix apps/stygian_web/assets

    command: |
      # Starting Phoenix
      export PATH="$HOME/.asdf/shims:$PATH"
      mix phx.server
