version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile  
      context: .
      args:
        # Elixir Version: 1.9, 1.10, 1.10.4, ...
        VARIANT: "1.15.4"
        # Node Version: 12, 14, ...
        NODE_VERSION: "18"
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    ports:
      - 4000:4000
    network_mode: service:db
  
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: stygian_dev
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    network_mode: host

volumes:
  postgres-data:            