name: Build Image for ACR
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: fbb83e90-95d8-4cb9-a001-3677d23852d4
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: b4a3e2d3-2d99-4b3e-a15e-5a85d655c544
          registry: stygianregistry
          repository: stygianregistry
          image: stygian
          git_access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          build_args: '[{"MAIL_PASS": "${{ secrets.MAIL_PASS }}"}]'

      # - name: Update Docker Compose
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.TEST_HOST }}
      #     username: ${{ secrets.TEST_USERNAME }}
      #     password: ${{ secrets.TEST_PASSWORD }}
      #     port: ${{ secrets.TEST_PORT }}
      #     script: /usr/bin/deploy.sh
